# Helm chart values for Development Deployment

# Development mode: we can enable debug mode
djangoDebug: true

# Django Secret Key
# This is overridden in eks-production1/dev/mop-dev-values.yaml
djangoSecretKey: "overridden"

# Microlensing Observation Portal Secret Values
# These are overridden in eks-production1/dev/mop-dev-values.yaml
antaresKey: ""
antaresPassword: ""
lcoApiKey: ""
lcoProposalId: ""
lcoUsername: ""

# AWS Credentials
# These are overridden in eks-production1/dev/mop-dev-values.yaml
awsAccessKeyId: ""
awsSecretAccessKey: ""
awsS3Bucket: ""

# Development mode: one replica is enough, we can live with short downtime
# if a machine fails or is taken offline for maintenance
replicaCount: 1

# PostgreSQL database configuration is used from values.yaml

# MOP Container CPU/Memory Resource Requests/Limits
resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

# HTTP Router Configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-private
    # Turn these on to disable all request buffering. In that case, you are on
    # your own in case of a DoS (Denial of Service) attack, or broken clients, or ..
    #nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: mop-dev.lco.gtn
      paths:
        - "/"

# CronJob: Fit Need Events
fitneedevents:
  enabled: false
  # Run in parallel across 6 Nodes (Machines) until all jobs are finished
  parallelism: 6
  # Use 3 CPU on each Node (Machine)
  cores: 3
  # CPU/Memory requests/limits
  resources:
    requests:
      cpu: 2
      memory: 512Mi
    limits:
      cpu: 3200m
      memory: 4096Mi

# CronJob: Run TAP
runtap:
  enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest ZTF DR3
# Logs into IPAC archive portal directly
harvestztfdr3:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest GAIA
harvestgaia:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest MOA
harvestmoa:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest OGLE
harvestogle:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Harvest ASAS-SN
harvestasassn:
  enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

# CronJob: Add Gaia Classifier
gaiaclassifier:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
